## Load in NumPy (pip install numpy )

In [1]:
import numpy as np

# The Basics

In [3]:
a = np.array([1,2,3])

print(a)

[1 2 3]


In [4]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
# Get Dimention

a.ndim

1

In [6]:
b.ndim

2

In [7]:
# Get Shape

b.shape

(2, 4)

In [8]:
# Get type

a.dtype

dtype('int32')

In [9]:
# Get size

a.itemsize

4

In [10]:
b.itemsize

4

In [11]:
# Get total size

a.nbytes

12

# Accessing/Changing specific elements, rows, columns, etc

In [21]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14,]])

c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [23]:
c.shape

(2, 7)

In [24]:
# get a specific element[r, c]

c[1, 5]

13

In [25]:
# Get a specific row

c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
# Get a specific column

c[:, 3]

array([ 4, 11])

In [28]:
# Getting a little more fancy(startindex:endindex:stepsize)

c[0, 1:6:2]

array([2, 4, 6])

In [30]:
c[0, 1:-1:2]

array([2, 4, 6])

In [32]:
c[1,5] = 20

c[:, 2] = [1,2]

print(c)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


# 3-D Example

In [33]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [34]:
# Get specific elements(work outside in)

b[0,1,1]

4

In [35]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [36]:
b[:,0,0]

array([1, 5])

In [37]:
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing different types of Arrays

In [38]:
# All 0s matrix

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [40]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [42]:
# All 1s matrix

np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [43]:
# Any other number

np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [45]:
# Any other number (full_like)

np.full_like(a, 4)

array([4, 4], dtype=object)

In [46]:
# Random decimal number

np.random.rand(4,2)

array([[0.63033216, 0.11246535],
       [0.16013531, 0.8189304 ],
       [0.55748871, 0.32008034],
       [0.84113854, 0.68734414]])

In [48]:
# Random Integer values

np.random.randint(4,7, size=(3,3))

array([[5, 6, 6],
       [5, 4, 4],
       [5, 5, 5]])

In [49]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
# Repeat an array
arr = np.array([[1,2,3]])

r1 = np.repeat(arr,3, axis=0)

print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [53]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Be careful when copying arrays!!!

In [54]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(b)

[100   2   3]


# Mathematics

In [55]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [56]:
a+2

array([3, 4, 5, 6])

In [57]:
a-2

array([-1,  0,  1,  2])

In [58]:
a *2

array([2, 4, 6, 8])

In [59]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [60]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [61]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [62]:
# Take the sin

np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [63]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

# Linear Algebra

In [64]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [65]:
b = np.full((3,2), 2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [66]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [67]:
# Find  the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [68]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

# Statistics

In [69]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
np.min(stats)

1

In [71]:
np.max(stats, axis=1)

array([3, 6])

In [72]:
np.sum(stats, axis=0)

array([5, 7, 9])

## Reorganizing Array

In [77]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [78]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [79]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [83]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [84]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])