# Lists

In [1]:
a = [1, 2, 3, 4, 5]

b = [ 10, 11, 12, 13, 14]

a + b

[1, 2, 3, 4, 5, 10, 11, 12, 13, 14]

In [2]:
result = []

for first, second in zip(a, b):
    result.append(first + second)
    
result

[11, 13, 15, 17, 19]

# NumPy

* Introducing Array

In [3]:
import numpy as np

In [4]:
# Simple Array Creation

a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [5]:
# Checking The Type

type(a)

numpy.ndarray

In [6]:
# Numeric "Type" of Elements

a.dtype

dtype('int32')

In [7]:
# Floating "Type" of Elements

f = np.array([1.5, 1.6, 2.1, 4.5])

f.dtype

dtype('float64')

In [8]:
# Array Indexing
a[0]

1

In [9]:
a[0] = 10

a

array([10,  2,  3,  4])

In [10]:
# beware of type coercion
a.dtype

dtype('int32')

In [11]:
# assigning a float into an int32 array truncates the decimal part

a[0] = 11.6

a

array([11,  2,  3,  4])

In [12]:
# fill has the same behavior

a.fill(-4.8)
a

array([-4, -4, -4, -4])

In [13]:
# Number of dimension
a.ndim

1

In [14]:
# # Array Shape
# Shape returns a tuple
# listing the length of the array along each dimension

a.shape

(4,)

In [15]:
# Total number of elements
a.size

#or
# bytes per elements

a.itemsize

4

In [16]:
## Bytes of Memory used
# return the number of bytes
# used by data portion of the array.

a.nbytes

16

# Array Operations

* Simple Array math

In [17]:
a

array([-4, -4, -4, -4])

In [18]:
f

array([1.5, 1.6, 2.1, 4.5])

In [19]:
a + f

array([-2.5, -2.4, -1.9,  0.5])

In [20]:
a * f

array([ -6. ,  -6.4,  -8.4, -18. ])

In [21]:
a / f

array([-2.66666667, -2.5       , -1.9047619 , -0.88888889])

In [22]:
f ** a

array([0.19753086, 0.15258789, 0.0514189 , 0.00243865])

In [23]:
a * 10

array([-40, -40, -40, -40])

### Math Function

In [24]:
# create array from 0 to 10

x = np.arange(11.)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
# Multipy entire array by scalar value

c = (2 * np.pi) / 10
c

0.6283185307179586

In [26]:
c * x

array([0.        , 0.62831853, 1.25663706, 1.88495559, 2.51327412,
       3.14159265, 3.76991118, 4.39822972, 5.02654825, 5.65486678,
       6.28318531])

In [27]:
# in-place operations

x *= c
x

array([0.        , 0.62831853, 1.25663706, 1.88495559, 2.51327412,
       3.14159265, 3.76991118, 4.39822972, 5.02654825, 5.65486678,
       6.28318531])

In [28]:
# apply function to array

y = np.sin(x)
y

array([ 0.00000000e+00,  5.87785252e-01,  9.51056516e-01,  9.51056516e-01,
        5.87785252e-01,  1.22464680e-16, -5.87785252e-01, -9.51056516e-01,
       -9.51056516e-01, -5.87785252e-01, -2.44929360e-16])

# Multi-Dimensional Array

In [29]:
a = np.array([[0,1,2,3,4], [10,11,12,13,14]])
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [30]:
# Shape=(Rows, columns)

a.shape

(2, 5)

In [31]:
# Element Count

a.size

10

In [32]:
# Number of Dimensions

a.ndim

2

In [33]:
# Get/ Set Elements
a[1, 3]

13

In [34]:
a [ 1, 3] = -1
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, -1, 14]])

In [35]:
# Address Second (Onth) Rw using Single index
a[1]

array([10, 11, 12, -1, 14])

In [36]:
a[0]

array([0, 1, 2, 3, 4])

# Indexing and Slicing

# Slicing
                    Var[lower: upper: step]

# Slicing Arrays

In [37]:
a = np.array([10,11,12,13,14,15])
a

array([10, 11, 12, 13, 14, 15])

In [38]:
a[1:3]

array([11, 12])

In [39]:
# negative indices work also

a[1:-2]

array([11, 12, 13])

In [40]:
a[-4 : 3]

array([12])

In [41]:
a[-4 : 2]

array([], dtype=int32)

## Omitting Indices

In [42]:
# omitted boundaries are assumed to be the beginning to be the beginning(or end ) of the list

# grab first three elements

a[: 3]

array([10, 11, 12])

In [43]:
# grab last two elements

a[-2 : ]

array([14, 15])

In [44]:
# every other element
a[:: 2]

array([10, 12, 14])

# Array Slicing

In [45]:
a = np.arange(36).reshape(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [46]:
a[0, 3:5]

array([3, 4])

In [47]:
a[4: , 4:]

array([[28, 29],
       [34, 35]])

In [48]:
a[: , 2]

array([ 2,  8, 14, 20, 26, 32])

In [49]:
# Strided are also posible

a[2::2, ::2]

array([[12, 14, 16],
       [24, 26, 28]])

## Slices are References

Slices are references to locations in memory. These memory locations can used in assignment operations.

In [50]:
a = np.array([0, 1, 2, 3, 4, 5])
a

array([0, 1, 2, 3, 4, 5])

In [51]:
# last two elements

a[-2: ]

array([4, 5])

In [52]:
# we can insert an iterable of length two

a[-2: ] = [-1, -2]
a

array([ 0,  1,  2,  3, -1, -2])

In [53]:
# or a scalar value

a[-2: ] = 88
a

array([ 0,  1,  2,  3, 88, 88])

In [54]:
b = np.arange(25).reshape(5,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
b[:, ::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

In [56]:
b[:, 1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [57]:
b[4: ]

array([[20, 21, 22, 23, 24]])

In [58]:
b[4, :]

array([20, 21, 22, 23, 24])

In [59]:
b[-1, :]

array([20, 21, 22, 23, 24])

In [60]:
b[1::2]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [61]:
b[1::2,  :3:2]

array([[ 5,  7],
       [15, 17]])

In [62]:
b[1::2,  :-1:2]

array([[ 5,  7],
       [15, 17]])

## Slicing Arrays Share Data

Arrays created by slicing share data with the originating array.
Changing values in a slice also changes the original array.

In [63]:
a = np.array([0,1,2,3,4, 5])
a

array([0, 1, 2, 3, 4, 5])

In [64]:
# Create a slice containg two elements of a
b = a[2:4]
b

array([2, 3])

In [65]:
b[0] = 10
b

array([10,  3])

In [66]:
# changing b changed a!
a

array([ 0,  1, 10,  3,  4,  5])

In [67]:
b = a[::]

In [68]:
b = a.copy()

In [69]:
a

array([ 0,  1, 10,  3,  4,  5])

In [70]:
b

array([ 0,  1, 10,  3,  4,  5])

# Fancy Indexing

In [71]:
# Indexing by position

a = np.arange(0,80,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [72]:
# fancy indexing

indices = [1, 2, -3]

y = a[indices]

y

array([10, 20, 50])

In [73]:
# this also works with setting

a[indices] = 88

a

array([ 0, 88, 88, 30, 40, 88, 60, 70])

In [74]:
# Indexing with booleans

In [75]:
# manual creation of masks

mask = np.array([0, 1, 1, 0, 0, 1, 0, 0], dtype=bool)
mask

array([False,  True,  True, False, False,  True, False, False])

In [76]:
# fancy indexing 
y = a[mask]
print(y)

[88 88 88]


# Fancy Indexing in 2-D

1. Create the array below with 
     a = np.arange(25).reshape(5,5)
    and find the some elements.
2. Extract all the numbers divisible by 3 using a boolean mask.

In [77]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [78]:
a[[0],[2]]

array([2])

In [79]:
a[[0,2],[2,3]]

array([ 2, 13])

In [80]:
a[[0,2,3,3],[2,3,1,4]]

array([ 2, 13, 16, 19])

In [81]:
a[[0,2,3,3],[2,3,1,-1]]

array([ 2, 13, 16, 19])

In [82]:
a %3

array([[0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0],
       [1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0]], dtype=int32)

In [83]:
a[a %3]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4]]])

In [84]:
a % 3 ==0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [85]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [86]:
a[a %3 == 0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

# Creating Arrays

* arange()
* linspace()
* array()
* zeros()
* ones()

In [87]:
# Floating point arrays

a = np.array([0, 1.0, 2, 3])
a.dtype

dtype('float64')

In [88]:
a.nbytes

32

In [89]:
# Reducing Precision

a = np.array([0,1.,2,3], dtype='float32')
a.dtype

dtype('float32')

In [90]:
a.nbytes

16

In [91]:
# Unsigned Integer Byte

a = np.array([0,1,2,3], dtype='uint8')
a.dtype

dtype('uint8')

In [92]:
a.nbytes

4

# Array Creation Functions

 # Arange
    
    numpy.arange([start, ]stop, [step, ]dtype=None)¶

Nearly identical to Python's range(). Creates an array of values in the range [start,stop) with 
the specified step value. Allows non-integer values for start, stop, and step.
Default dtype is derived from the start, stop,and step values.

In [93]:
np.arange(4)

array([0, 1, 2, 3])

In [94]:
pi = 3.14

In [95]:
np.arange(0, 2*pi, pi/4)

array([0.   , 0.785, 1.57 , 2.355, 3.14 , 3.925, 4.71 , 5.495])

In [96]:
# be careful...

np.arange(1.5, 2.1, 0.3)

array([1.5, 1.8, 2.1])

# Ones, Zeros

*shape *  is a number or sequence specifying the dimensions of the array. if dtype is not specified, it defaults to float64. 

In [97]:
np.ones((2,3), dtype='float32')

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [98]:
np.zeros(3)

array([0., 0., 0.])

# Identity

In [99]:
# Generate an n by n identity array. The default is float64.

a = np.identity(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [100]:
a.dtype

dtype('float64')

In [101]:
np.identity(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# Empty and Fill

empty(shape, dtype=float64, order='C')

In [102]:
np.empty(2)

array([5.43230922e-312, 7.29112202e-304])

In [103]:
# array filled with 5.0

a = np.full(2, 5.0)
a

array([5., 5.])

In [104]:
# alternative approaches (slower)

a = np.empty(2)
a.fill(4.0)
a

array([4., 4.])

In [105]:
a[:] = 3.0
a

array([3., 3.])

# Linspace

In [106]:
# Generate N evenly spaced elements between (and including) start and stop values.

np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [107]:
# Logspace

# Generate N evenly spaced elements on a log scale between base **start and base**stop(default base = 10)

np.logspace(0, 1, 5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

# Array Calculation Methods in NumPy

Rule 1: Operations between multiple array objects are first checked for proper shape match.

Rule 2: Mathematical operators(+, -, *, /, exp, log,...) apply element by element, on the values.

Rule 3: Reduction operations(mean, std, skew, kurt, sum, prod,...) apply to the whole array, unless an exist is specified.

Rule 4: Missing values propagate unless explicitly ignored(nanmean, nansum,...)

In [108]:
# sum method

a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
# .sum() defaults to adding up all the values in an array.

a.sum()

21

In [110]:
# or
np.sum(a)

21

In [111]:
# sum along the 0th axis

a.sum(axis=0)

array([5, 7, 9])

In [112]:
# or
np.sum(a, axis =0)

array([5, 7, 9])

In [113]:
# sum along the last axis
a.sum(axis  = -1)

array([ 6, 15])

In [114]:
a.sum(axis = 1)

array([ 6, 15])

# Min/ Max

In [115]:
a = np.array([[2,3], [0, 1]])
a

array([[2, 3],
       [0, 1]])

In [116]:
# Minimum value  in the array
np.min(a)

0

In [117]:
# or
a.min()

0

In [118]:
# Max
a.max()

3

In [119]:
# max values for one dimension

a.max(axis=0)

array([2, 3])

In [120]:
# as a function

np.max(a, axis=1)

array([3, 1])

In [121]:
# ArgMin/Max

In [122]:
a.argmax()

1

In [123]:
a.argmin()

2

# Unraveling 

In [124]:
# Numpy includes a function to un-flatten 1D locations

np.unravel_index(a.argmax(), a.shape)

(0, 1)

# Where

## Coordinate Locations

* NumPy's where function has two distinct uses. Ones is to provide coordinates from masks

In [125]:
a = np.array([-1, 2, 5, 5])

In [126]:
a == a.max()

array([False, False,  True,  True])

In [127]:
np.where(a==a.max())

(array([2, 3], dtype=int64),)

In [128]:
np.where(a > 0)

(array([1, 2, 3], dtype=int64),)

In [129]:
b = np.arange(-2, 2) ** 2
b

array([4, 1, 0, 1], dtype=int32)

In [130]:
mask = b % 2 == 0
mask

array([ True, False,  True, False])

In [131]:
# Coordinates are returned as a tuple of arrays, one for each axis
np.where(mask)

(array([0, 2], dtype=int64),)

# Conditional Array  Creation

In [132]:
# Where can also be used to construct a new array by choosing values from other arrays of the same shape

positives = np.arange(4)
negatives = -positives
np.where(mask, positives, negatives)

array([ 0, -1,  2, -3])

In [133]:
# Or from scalar values. This can be useful for recording arrays

np.where(mask, 1, 0)

array([1, 0, 1, 0])

In [134]:
# Or from both

np.where(mask, positives, 0)

array([0, 0, 2, 0])

# Statistical Array methods

In [135]:
# Mean

a = np.array([[1,2,3,4],[5,6,7,8]])

# mean value of each column

a.mean(axis=0)

array([3., 4., 5., 6.])

In [136]:
# Or
np.mean(a, axis=0)

array([3., 4., 5., 6.])

# Standard Dev. / Variance

In [137]:
# Standard Deviation

a.std(axis =0)

array([2., 2., 2., 2.])

In [138]:
# For sample, set ddof=1

a.std(axis=0, ddof=1)

array([2.82842712, 2.82842712, 2.82842712, 2.82842712])

In [139]:
# Variance
a.var(axis=0)

array([4., 4., 4., 4.])

In [140]:
np.var(a, axis=0)

array([4., 4., 4., 4.])

# Data Importing

In [141]:
# ref: 'wind-statistics-solution'

In [142]:
from numpy import loadtxt

In [143]:
data = loadtxt('wind.data')
data

array([[61.  ,  1.  ,  1.  , ..., 12.58, 18.5 , 15.04],
       [61.  ,  1.  ,  2.  , ...,  9.67, 17.54, 13.83],
       [61.  ,  1.  ,  3.  , ...,  7.67, 12.75, 12.71],
       ...,
       [78.  , 12.  , 29.  , ..., 16.42, 18.88, 29.58],
       [78.  , 12.  , 30.  , ..., 12.12, 14.67, 28.79],
       [78.  , 12.  , 31.  , ..., 11.38, 12.08, 22.08]])

In [144]:
data.shape

(6574, 15)

In [145]:
data[: 4]

array([[61.  ,  1.  ,  1.  , 15.04, 14.96, 13.17,  9.29, 13.96,  9.87,
        13.67, 10.25, 10.83, 12.58, 18.5 , 15.04],
       [61.  ,  1.  ,  2.  , 14.71, 16.88, 10.83,  6.5 , 12.62,  7.67,
        11.5 , 10.04,  9.79,  9.67, 17.54, 13.83],
       [61.  ,  1.  ,  3.  , 18.5 , 16.88, 12.33, 10.13, 11.17,  6.17,
        11.25,  8.04,  8.5 ,  7.67, 12.75, 12.71],
       [61.  ,  1.  ,  4.  , 10.58,  6.63, 11.75,  4.58,  4.54,  2.88,
         8.63,  1.79,  5.83,  5.88,  5.46, 10.88]])

In [146]:
data[:, :3]

array([[61.,  1.,  1.],
       [61.,  1.,  2.],
       [61.,  1.,  3.],
       ...,
       [78., 12., 29.],
       [78., 12., 30.],
       [78., 12., 31.]])

In [147]:
data[:, 3:]

array([[15.04, 14.96, 13.17, ..., 12.58, 18.5 , 15.04],
       [14.71, 16.88, 10.83, ...,  9.67, 17.54, 13.83],
       [18.5 , 16.88, 12.33, ...,  7.67, 12.75, 12.71],
       ...,
       [14.  , 10.29, 14.42, ..., 16.42, 18.88, 29.58],
       [18.5 , 14.04, 21.29, ..., 12.12, 14.67, 28.79],
       [20.33, 17.41, 27.29, ..., 11.38, 12.08, 22.08]])

# The Array Data Structure in NumPy

# Operation on the array structure

Operations that only affect structure, not the data, can usually be executed without copying memory.

In [148]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [149]:
b = a.reshape(2, 3)
b            
# This is not a new copy of the data. The original data does not get reordered.

array([[0, 1, 2],
       [3, 4, 5]])

## Transpose

In [150]:
a = np.array([[0,1,2], [3,4,5]])

a.shape

(2, 3)

In [151]:
# transpose swaps the order of axes

a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [152]:
a.T.shape

(3, 2)

###  Transpose Returns Views

In [153]:
# Transpose does not move values around in memory. It only changes the order of "strides"
# in the array

In [154]:
a.strides

(12, 4)

In [155]:
a.T.strides

(4, 12)

## Reshaping Arrays

In [156]:
c = np.array([[0,1,2,3],[4,5,6,7]])
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [157]:
# Reshape cannot change the number of elements in an array
c.reshape(3,2)

ValueError: cannot reshape array of size 8 into shape (3,2)

In [158]:
c.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

## Flattening Arrays

# Flatten(Safe)

* a.flatten() converts a multi-dimensional array into a 1-D array. The new array is a copy of the original data.

In [159]:
# Create a 2D array

a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [160]:
# Flatten out elements to 1D

b = a.flatten()
b

array([0, 1, 2, 3, 4, 5])

In [161]:
# Changing b does not change a

b[0] = 10
b

array([10,  1,  2,  3,  4,  5])

In [162]:
a # value 1st position in does not change

array([[0, 1, 2],
       [3, 4, 5]])

## Ravel (Efficient)

*a.ravel()*  is the same as *a.flatten()*, but returns a reference(or view)
of the array if possible(i.e the memory is contiguous). otherwise the new array copies the data.

In [163]:
# Flatten ot elements to 1D 

b = a.ravel()
b

array([0, 1, 2, 3, 4, 5])

In [164]:
# Changing b does change a

b[0] = 10
b

array([10,  1,  2,  3,  4,  5])

In [165]:
a

array([[10,  1,  2],
       [ 3,  4,  5]])

# Array Broadcasting in NumPy

* NumPy arrays of different dimensionality can be combined in the same expression. Arrays with smaller dimension are *broadcasted* to match the larger arrays, without copying data. Broadcasting
has two rules.

### Rule 1: Prepend Ones to the Smaller Array's Shape

In [166]:
import numpy as np

a = np.ones((3, 5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [167]:
b = np.ones((5, ))
b

array([1., 1., 1., 1., 1.])

In [168]:
b.reshape(1,5)

array([[1., 1., 1., 1., 1.]])

In [169]:
b[np.newaxis, :]

array([[1., 1., 1., 1., 1.]])

#### Rule 2: Dimensions of Size 1 are repeated without Copying


In [170]:
c = a + b # c.shape ==(3,5)
c

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [171]:
tmp_b = b.reshape(1, 5)
tmp_b

array([[1., 1., 1., 1., 1.]])

In [172]:
tmp_b_repeat = tmp_b.repeat(3, axis=0)
tmp_b_repeat

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [173]:
c = a + tmp_b_repeat
c

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [174]:
# Broadcasting in Action

a = np.array([0, 10, 20, 30])
a

array([ 0, 10, 20, 30])

In [175]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [176]:
y = a[:,np. newaxis] + b
y

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

# Broadcasting's Usefulness

* Broadcasting can often be used to replace needless data replication inside a Numpy array expression.

* np.meshgrid() - use newaxis appropriately in broadcasting expressions.

* np.repeat() - broadcasting makes repeating an array along a dimension of size 1 unnessarry.

In [177]:
# MeshGrid: Copies Data

x, y = np.meshgrid([1,2], [3,4,5])

z = x + y
z

array([[4, 5],
       [5, 6],
       [6, 7]])

In [178]:
# Broadcasting: No Copies

x = np.array([1, 2])

y = np.array([3, 4, 5])

z = x[np.newaxis, :] + y[:, np.newaxis]
z

array([[4, 5],
       [5, 6],
       [6, 7]])

# Broadcasting, NumPy API, SciPy.org.

https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html

# Universal Function Methods

The mathematical, comparative, logical, and bitwise operators op that take two arguments(binary operators)
 have special methods that operate on arrays:

# op.reducer(a, axis = 0)

op.reducer(a) applies op to all the elements in a 1D array a reducing it to a single value.

In [179]:
# Add Example
import numpy as np
a = np.array([1,2,3,4])
np.add.reduce(a)

10

In [180]:
# String List Example

a = np.array(['ab','cd','ef'], dtype='object')

np.add.reduce(a)

'abcdef'

In [181]:
# logical OP Examples

a = np.array([1,1,0,1])
np.logical_and.reduce(a)

False

In [182]:
np.logical_or.reduce(a)

True

For multidimensional arrays, op.reduce(a, axis) applies op to the elements of a along the specified axis. The resulting array has dimensionality one less
than a. The default value for axis is 0.

In [183]:
# Summing UP Each Row
a = np.arange(3) + np.arange(0, 40, 10 ).reshape(-1, 1)
a

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [184]:
np.add.reduce(a,1)

array([ 3, 33, 63, 93])

In [185]:
# Sum Columns by Default

np.add.reduce(a)

array([60, 64, 68])

# op.accumulate()
op. accumulaate(a) create a new array containing the intermediate results of the reduce operation at each element in a.

In [186]:
# Add Example

a = np.array([1,2,3,4])
np.add.accumulate(a)

array([ 1,  3,  6, 10], dtype=int32)

In [187]:
# String List Example

a = np.array(['ab', 'cd', 'ef'], dtype='object')

np.add.accumulate(a)

array(['ab', 'abcd', 'abcdef'], dtype=object)

In [188]:
# Logical OP Examples

a = np.array([1,1,0])
np.logical_and.accumulate(a)

array([ True,  True, False])

In [189]:
np.logical_or.accumulate(a)

array([ True,  True,  True])

## op.reduceat()

op.reduceat(a, indices) applies op to ranges in the 1D array a defined by the values in indices. The resulting array has the same length as indices.

In [190]:
a = np.array([0,10,20,30,40,50])

indices = np.array([1,4])

np.add.reduceat(a, indices)

array([60, 90], dtype=int32)